#!/bin/bash
ARG1=${1:?"Enter the login, please"}
VAR_W=$(who | grep $ARG1 | awk '$2 ~/pts*/ {print $1}')
VAR_ID=$(cat /etc/passwd | awk -F: '/'$ARG1'/{print $3}')
if test -z $VAR_W
then
    echo "No $ARG1 right now"
else
    echo "The login is $ARG1 and the ID is $VAR_ID."
    echo "The $ARG1's killer is processing ... "
    sleep 3
    sudo pkill -u $VAR_ID
    sed -n '/"$ARG1"/{p;q}' /etc/passwd
fi
echo "So, "$ARG1" doesn't exist"